name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Ucab Profile 🔽
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd /var/www/ER-frontend
            git checkout main
            git pull || { echo 'Failed to pull changes'; exit 1; }

      - name: Npm Install Frontend ⚙️
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd /var/www/ER-frontend
            git checkout main
            npm install || { echo 'Failed to install dependencies'; exit 1; }

      - name: Remove existing dist folder ❌
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd /var/www/ER-frontend
            rm -rf dist || { echo 'Failed to remove existing dist folder'; exit 1; }

      - name: Build and Verify 👷‍♂️
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd /var/www/ER-frontend
            if npm run build; then
              echo 'Build successful'
            else
              echo 'Build failed'
              exit 1
            fi

      - name: Finalize ✅
        run: |
          echo 'Repository already exists previously, pulling changes'
