name: Build & Deploy
on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy UcabProfile Frontend
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            cd /var/www 
            cd ER-frontend-staging
            git checkout staging
            git pull || exit 1
            npm install || exit 1

            # Agrega comandos para liberar recursos o archivos bloqueados
            chmod -R 777 dist || exit 1
            rm -rf dist || exit 1
            # Ejecuta npm run build y verifica el resultado
            if npm run build; then
              echo 'Build successful'
            else
              echo 'Build failed'
              exit 1
            fi
            echo 'Repository already exists previously, pulling changes'
